spring:
  application:
    name: devices-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devices}
    username: ${DB_USERNAME:devices}
    password: ${DB_PASSWORD:devices}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
